# Generated by Django 5.2 on 2025-04-16 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requester_name", models.CharField(max_length=100)),
                ("requester_email", models.EmailField(max_length=254)),
                ("requester_phone", models.CharField(max_length=15)),
                ("patient_name", models.CharField(max_length=100)),
                ("patient_age", models.PositiveIntegerField()),
                (
                    "patient_gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("units_required", models.PositiveIntegerField(default=1)),
                ("hospital_name", models.CharField(max_length=200)),
                ("hospital_address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("reason", models.TextField(help_text="Reason for blood request")),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("needed_by_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("attended_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "attended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
    ]
